# Generated by Django 4.2.19 on 2025-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Classroom", "0004_auto_20210422_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
